name: Scala CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.10.1_3.5.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify sbt version
        run: sbt sbtVersion

      - name: Run tests with coverage
        run: sbt clean coverage test coverageReport

      - name: Save coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: target/scala-*/scoverage-*
